# Generated by Django 5.1.6 on 2025-04-03 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0017_funcionario_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='funcao',
            field=models.CharField(choices=[('Diretor(a)', 'Diretor(a)'), ('Secretario(a)', 'Secretário(a)'), ('Coordenador(a)', 'Coordenador(a)'), ('Agente Administrativo', 'Agente Administrativo'), ('Auxiliar Administrativo', 'Auxiliar Administrativo')], max_length=30),
        ),
    ]
