# Generated by Django 5.1.7 on 2025-04-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0018_alter_funcionario_funcao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='funcao',
            field=models.CharField(choices=[('Administrador', 'Administrador(a)'), ('Diretor(a)', 'Diretor(a)'), ('Secretario(a)', 'Secretário(a)'), ('Coordenador(a)', 'Coordenador(a)'), ('Agente Administrativo', 'Agente Administrativo'), ('Auxiliar Administrativo', 'Auxiliar Administrativo')], max_length=30),
        ),
    ]
