services:
  - type: web
    name: gestao-escolar
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn gestao_escolar.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: nomedobanco
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
    plan: free

databases:
  - name: nomedobanco
