# Generated by Django 5.1.7 on 2025-04-08 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('funcao', models.CharField(max_length=50)),
                ('carga_horaria_semanal', models.IntegerField()),
                ('carga_horaria_mensal', models.IntegerField()),
                ('planejamento', models.BooleanField(default=False)),
                ('aluno_especial', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FolhaMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=20)),
                ('ano', models.IntegerField()),
                ('faltas', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('diarias_qtd', models.PositiveIntegerField(blank=True, null=True)),
                ('diarias_horas', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('servidor_substituto', models.CharField(blank=True, max_length=100, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.funcionario')),
            ],
        ),
    ]
