# Generated by Django 5.1.7 on 2025-04-08 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folhamensal',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folhas', to='funcionarios.funcionario'),
        ),
        migrations.AlterField(
            model_name='folhamensal',
            name='servidor_substituto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substituicoes', to='funcionarios.funcionario', verbose_name='Servidor Substituto'),
        ),
    ]
